# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4bada923cdbb41c0d01bafef1d42ae874ada50f8d5f0b05133301fefb8dbdce1537f16a84b0c42639e300988b916b03f7a75d3bc88b676955e965359dc130088

test:
  secret_key_base: cd9636d29f2e2c98b4c2d5ad79e8a622b4de18358dfd8d7f3d6d39912c1cdd4950155c4a47ff56f000388e14b433f3d020e20274fcbb5d67fd93db0217376ba7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
